version: "3.8"
services:
  axon-server:
    image: axoniq/axonserver:4.3.6
    hostname: axonserver
    container_name: axon-server
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224
    environment:
      AXONIQ_AXONSERVER_NAME: windpath_axonserver
      AXONSERVER_HOSTNAME: axonserver
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: "true"
  proxy:
    build:
      context: ./proxy/
      dockerfile: ./Dockerfile
    image: windpath/proxy:latest
    ports:
      - "8082:8082"
      - "9901:9901"
  web:
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    image: windpath/web:latest
    ports:
      - "8081:80"
  grpcox:
    image: gusaul/grpcox:latest
    volumes:
      - ./log:/log
    ports:
      - "8084:6969"
volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
