version: "3.8"
services:
  axon-server:
    image: axoniq/axonserver:4.5
    hostname: axonserver
    container_name: axon-server
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config
    networks:
      path-network:
        aliases:
          - axon-server
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224
    environment:
      AXONIQ_AXONSERVER_NAME: windpath_axonserver
      AXONSERVER_HOSTNAME: axonserver
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: "true"
  proxy:
    build:
      context: ./proxy/
      dockerfile: ./Dockerfile
    image: windpath/proxy:latest
    networks:
      path-network:
        aliases:
          - proxy
    ports:
      - "8082:8082"
      - "9901:9901"
  web:
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    image: windpath/web:latest
    networks:
      path-network:
        aliases:
          - web
    ports:
      - "8081:80"
#  path-service:
#    build:
#      context: .
#      dockerfile: services/path/app/Dockerfile
#    image: windpath/path-service-app:latest
#    networks:
#      path-network:
#        aliases:
#          - path-service
#    ports:
#      - "8085:9000"
  grpcox:
    image: gusaul/grpcox:latest
    networks:
      - path-network
    volumes:
      - ./log:/log
    ports:
      - "8084:6969"
volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
networks:
  path-network: