// source: pathcommands.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.path.commands.CreatePathFromGpxCommand', null, global);
goog.exportSymbol('proto.path.commands.GenericResponse', null, global);
goog.exportSymbol('proto.path.commands.PathCommand', null, global);
goog.exportSymbol('proto.path.commands.PathCommand.CommandCase', null, global);
goog.exportSymbol('proto.path.commands.PathCreatedFromGpxEvent', null, global);
goog.exportSymbol('proto.path.commands.PathRenamedEvent', null, global);
goog.exportSymbol('proto.path.commands.ProtoUUID', null, global);
goog.exportSymbol('proto.path.commands.RenamePathCommand', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.commands.PathCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.path.commands.PathCommand.oneofGroups_);
};
goog.inherits(proto.path.commands.PathCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.commands.PathCommand.displayName = 'proto.path.commands.PathCommand';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.commands.CreatePathFromGpxCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.commands.CreatePathFromGpxCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.commands.CreatePathFromGpxCommand.displayName = 'proto.path.commands.CreatePathFromGpxCommand';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.commands.RenamePathCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.commands.RenamePathCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.commands.RenamePathCommand.displayName = 'proto.path.commands.RenamePathCommand';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.commands.PathCreatedFromGpxEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.commands.PathCreatedFromGpxEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.commands.PathCreatedFromGpxEvent.displayName = 'proto.path.commands.PathCreatedFromGpxEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.commands.PathRenamedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.commands.PathRenamedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.commands.PathRenamedEvent.displayName = 'proto.path.commands.PathRenamedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.commands.GenericResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.commands.GenericResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.commands.GenericResponse.displayName = 'proto.path.commands.GenericResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.commands.ProtoUUID = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.commands.ProtoUUID, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.commands.ProtoUUID.displayName = 'proto.path.commands.ProtoUUID';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.path.commands.PathCommand.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.path.commands.PathCommand.CommandCase = {
  COMMAND_NOT_SET: 0,
  CREATEPATHFROMGPXCOMMAND: 2,
  RENAMEPATHCOMMAND: 3
};

/**
 * @return {proto.path.commands.PathCommand.CommandCase}
 */
proto.path.commands.PathCommand.prototype.getCommandCase = function() {
  return /** @type {proto.path.commands.PathCommand.CommandCase} */(jspb.Message.computeOneofCase(this, proto.path.commands.PathCommand.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.commands.PathCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.path.commands.PathCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.commands.PathCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.PathCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.path.commands.ProtoUUID.toObject(includeInstance, f),
    createpathfromgpxcommand: (f = msg.getCreatepathfromgpxcommand()) && proto.path.commands.CreatePathFromGpxCommand.toObject(includeInstance, f),
    renamepathcommand: (f = msg.getRenamepathcommand()) && proto.path.commands.RenamePathCommand.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.commands.PathCommand}
 */
proto.path.commands.PathCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.commands.PathCommand;
  return proto.path.commands.PathCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.commands.PathCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.commands.PathCommand}
 */
proto.path.commands.PathCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.path.commands.ProtoUUID;
      reader.readMessage(value,proto.path.commands.ProtoUUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto.path.commands.CreatePathFromGpxCommand;
      reader.readMessage(value,proto.path.commands.CreatePathFromGpxCommand.deserializeBinaryFromReader);
      msg.setCreatepathfromgpxcommand(value);
      break;
    case 3:
      var value = new proto.path.commands.RenamePathCommand;
      reader.readMessage(value,proto.path.commands.RenamePathCommand.deserializeBinaryFromReader);
      msg.setRenamepathcommand(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.commands.PathCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.commands.PathCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.commands.PathCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.PathCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.path.commands.ProtoUUID.serializeBinaryToWriter
    );
  }
  f = message.getCreatepathfromgpxcommand();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.path.commands.CreatePathFromGpxCommand.serializeBinaryToWriter
    );
  }
  f = message.getRenamepathcommand();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.path.commands.RenamePathCommand.serializeBinaryToWriter
    );
  }
};


/**
 * optional ProtoUUID id = 1;
 * @return {?proto.path.commands.ProtoUUID}
 */
proto.path.commands.PathCommand.prototype.getId = function() {
  return /** @type{?proto.path.commands.ProtoUUID} */ (
    jspb.Message.getWrapperField(this, proto.path.commands.ProtoUUID, 1));
};


/**
 * @param {?proto.path.commands.ProtoUUID|undefined} value
 * @return {!proto.path.commands.PathCommand} returns this
*/
proto.path.commands.PathCommand.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.commands.PathCommand} returns this
 */
proto.path.commands.PathCommand.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.commands.PathCommand.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CreatePathFromGpxCommand createPathFromGpxCommand = 2;
 * @return {?proto.path.commands.CreatePathFromGpxCommand}
 */
proto.path.commands.PathCommand.prototype.getCreatepathfromgpxcommand = function() {
  return /** @type{?proto.path.commands.CreatePathFromGpxCommand} */ (
    jspb.Message.getWrapperField(this, proto.path.commands.CreatePathFromGpxCommand, 2));
};


/**
 * @param {?proto.path.commands.CreatePathFromGpxCommand|undefined} value
 * @return {!proto.path.commands.PathCommand} returns this
*/
proto.path.commands.PathCommand.prototype.setCreatepathfromgpxcommand = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.path.commands.PathCommand.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.commands.PathCommand} returns this
 */
proto.path.commands.PathCommand.prototype.clearCreatepathfromgpxcommand = function() {
  return this.setCreatepathfromgpxcommand(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.commands.PathCommand.prototype.hasCreatepathfromgpxcommand = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional RenamePathCommand renamePathCommand = 3;
 * @return {?proto.path.commands.RenamePathCommand}
 */
proto.path.commands.PathCommand.prototype.getRenamepathcommand = function() {
  return /** @type{?proto.path.commands.RenamePathCommand} */ (
    jspb.Message.getWrapperField(this, proto.path.commands.RenamePathCommand, 3));
};


/**
 * @param {?proto.path.commands.RenamePathCommand|undefined} value
 * @return {!proto.path.commands.PathCommand} returns this
*/
proto.path.commands.PathCommand.prototype.setRenamepathcommand = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.path.commands.PathCommand.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.commands.PathCommand} returns this
 */
proto.path.commands.PathCommand.prototype.clearRenamepathcommand = function() {
  return this.setRenamepathcommand(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.commands.PathCommand.prototype.hasRenamepathcommand = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.commands.CreatePathFromGpxCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.path.commands.CreatePathFromGpxCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.commands.CreatePathFromGpxCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.CreatePathFromGpxCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.commands.CreatePathFromGpxCommand}
 */
proto.path.commands.CreatePathFromGpxCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.commands.CreatePathFromGpxCommand;
  return proto.path.commands.CreatePathFromGpxCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.commands.CreatePathFromGpxCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.commands.CreatePathFromGpxCommand}
 */
proto.path.commands.CreatePathFromGpxCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.commands.CreatePathFromGpxCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.commands.CreatePathFromGpxCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.commands.CreatePathFromGpxCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.CreatePathFromGpxCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.path.commands.CreatePathFromGpxCommand.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.path.commands.CreatePathFromGpxCommand} returns this
 */
proto.path.commands.CreatePathFromGpxCommand.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.commands.RenamePathCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.path.commands.RenamePathCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.commands.RenamePathCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.RenamePathCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.commands.RenamePathCommand}
 */
proto.path.commands.RenamePathCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.commands.RenamePathCommand;
  return proto.path.commands.RenamePathCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.commands.RenamePathCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.commands.RenamePathCommand}
 */
proto.path.commands.RenamePathCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.commands.RenamePathCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.commands.RenamePathCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.commands.RenamePathCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.RenamePathCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.path.commands.RenamePathCommand.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.path.commands.RenamePathCommand} returns this
 */
proto.path.commands.RenamePathCommand.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.commands.PathCreatedFromGpxEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.path.commands.PathCreatedFromGpxEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.commands.PathCreatedFromGpxEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.PathCreatedFromGpxEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.path.commands.ProtoUUID.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.commands.PathCreatedFromGpxEvent}
 */
proto.path.commands.PathCreatedFromGpxEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.commands.PathCreatedFromGpxEvent;
  return proto.path.commands.PathCreatedFromGpxEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.commands.PathCreatedFromGpxEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.commands.PathCreatedFromGpxEvent}
 */
proto.path.commands.PathCreatedFromGpxEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.path.commands.ProtoUUID;
      reader.readMessage(value,proto.path.commands.ProtoUUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.commands.PathCreatedFromGpxEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.commands.PathCreatedFromGpxEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.commands.PathCreatedFromGpxEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.PathCreatedFromGpxEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.path.commands.ProtoUUID.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ProtoUUID id = 1;
 * @return {?proto.path.commands.ProtoUUID}
 */
proto.path.commands.PathCreatedFromGpxEvent.prototype.getId = function() {
  return /** @type{?proto.path.commands.ProtoUUID} */ (
    jspb.Message.getWrapperField(this, proto.path.commands.ProtoUUID, 1));
};


/**
 * @param {?proto.path.commands.ProtoUUID|undefined} value
 * @return {!proto.path.commands.PathCreatedFromGpxEvent} returns this
*/
proto.path.commands.PathCreatedFromGpxEvent.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.commands.PathCreatedFromGpxEvent} returns this
 */
proto.path.commands.PathCreatedFromGpxEvent.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.commands.PathCreatedFromGpxEvent.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.path.commands.PathCreatedFromGpxEvent.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.path.commands.PathCreatedFromGpxEvent} returns this
 */
proto.path.commands.PathCreatedFromGpxEvent.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.commands.PathRenamedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.path.commands.PathRenamedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.commands.PathRenamedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.PathRenamedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.path.commands.ProtoUUID.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.commands.PathRenamedEvent}
 */
proto.path.commands.PathRenamedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.commands.PathRenamedEvent;
  return proto.path.commands.PathRenamedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.commands.PathRenamedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.commands.PathRenamedEvent}
 */
proto.path.commands.PathRenamedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.path.commands.ProtoUUID;
      reader.readMessage(value,proto.path.commands.ProtoUUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.commands.PathRenamedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.commands.PathRenamedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.commands.PathRenamedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.PathRenamedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.path.commands.ProtoUUID.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ProtoUUID id = 1;
 * @return {?proto.path.commands.ProtoUUID}
 */
proto.path.commands.PathRenamedEvent.prototype.getId = function() {
  return /** @type{?proto.path.commands.ProtoUUID} */ (
    jspb.Message.getWrapperField(this, proto.path.commands.ProtoUUID, 1));
};


/**
 * @param {?proto.path.commands.ProtoUUID|undefined} value
 * @return {!proto.path.commands.PathRenamedEvent} returns this
*/
proto.path.commands.PathRenamedEvent.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.commands.PathRenamedEvent} returns this
 */
proto.path.commands.PathRenamedEvent.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.commands.PathRenamedEvent.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.path.commands.PathRenamedEvent.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.path.commands.PathRenamedEvent} returns this
 */
proto.path.commands.PathRenamedEvent.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.commands.GenericResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.path.commands.GenericResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.commands.GenericResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.GenericResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.commands.GenericResponse}
 */
proto.path.commands.GenericResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.commands.GenericResponse;
  return proto.path.commands.GenericResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.commands.GenericResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.commands.GenericResponse}
 */
proto.path.commands.GenericResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.commands.GenericResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.commands.GenericResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.commands.GenericResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.GenericResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.path.commands.GenericResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.path.commands.GenericResponse} returns this
 */
proto.path.commands.GenericResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.path.commands.GenericResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.path.commands.GenericResponse} returns this
 */
proto.path.commands.GenericResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.commands.ProtoUUID.prototype.toObject = function(opt_includeInstance) {
  return proto.path.commands.ProtoUUID.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.commands.ProtoUUID} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.ProtoUUID.toObject = function(includeInstance, msg) {
  var f, obj = {
    mostsigbits: jspb.Message.getFieldWithDefault(msg, 1, 0),
    leastsigbits: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.commands.ProtoUUID}
 */
proto.path.commands.ProtoUUID.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.commands.ProtoUUID;
  return proto.path.commands.ProtoUUID.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.commands.ProtoUUID} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.commands.ProtoUUID}
 */
proto.path.commands.ProtoUUID.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSfixed64());
      msg.setMostsigbits(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSfixed64());
      msg.setLeastsigbits(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.commands.ProtoUUID.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.commands.ProtoUUID.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.commands.ProtoUUID} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.commands.ProtoUUID.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMostsigbits();
  if (f !== 0) {
    writer.writeSfixed64(
      1,
      f
    );
  }
  f = message.getLeastsigbits();
  if (f !== 0) {
    writer.writeSfixed64(
      2,
      f
    );
  }
};


/**
 * optional sfixed64 mostSigBits = 1;
 * @return {number}
 */
proto.path.commands.ProtoUUID.prototype.getMostsigbits = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.path.commands.ProtoUUID} returns this
 */
proto.path.commands.ProtoUUID.prototype.setMostsigbits = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional sfixed64 leastSigBits = 2;
 * @return {number}
 */
proto.path.commands.ProtoUUID.prototype.getLeastsigbits = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.path.commands.ProtoUUID} returns this
 */
proto.path.commands.ProtoUUID.prototype.setLeastsigbits = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.path.commands);
