// source: pathEvents.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gpx_pb = require('./gpx_pb.js');
goog.object.extend(proto, gpx_pb);
var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
goog.exportSymbol('proto.path.domain.PathCreatedFromGpxEvent', null, global);
goog.exportSymbol('proto.path.domain.PathRemovedEvent', null, global);
goog.exportSymbol('proto.path.domain.PathRenamedEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.domain.PathCreatedFromGpxEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.domain.PathCreatedFromGpxEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.domain.PathCreatedFromGpxEvent.displayName = 'proto.path.domain.PathCreatedFromGpxEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.domain.PathRenamedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.domain.PathRenamedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.domain.PathRenamedEvent.displayName = 'proto.path.domain.PathRenamedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path.domain.PathRemovedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path.domain.PathRemovedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.path.domain.PathRemovedEvent.displayName = 'proto.path.domain.PathRemovedEvent';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.path.domain.PathCreatedFromGpxEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.domain.PathCreatedFromGpxEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.domain.PathCreatedFromGpxEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && common_pb.ProtoUUID.toObject(includeInstance, f),
    track: (f = msg.getTrack()) && gpx_pb.Track.toObject(includeInstance, f),
    time: (f = msg.getTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    bounds: (f = msg.getBounds()) && gpx_pb.Bounds.toObject(includeInstance, f),
    maxspeedpoint: (f = msg.getMaxspeedpoint()) && gpx_pb.Point.toObject(includeInstance, f),
    duration: (f = msg.getDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    averagespeed: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    distance: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent}
 */
proto.path.domain.PathCreatedFromGpxEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.domain.PathCreatedFromGpxEvent;
  return proto.path.domain.PathCreatedFromGpxEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.domain.PathCreatedFromGpxEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent}
 */
proto.path.domain.PathCreatedFromGpxEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.ProtoUUID;
      reader.readMessage(value,common_pb.ProtoUUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = new gpx_pb.Track;
      reader.readMessage(value,gpx_pb.Track.deserializeBinaryFromReader);
      msg.setTrack(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 5:
      var value = new gpx_pb.Bounds;
      reader.readMessage(value,gpx_pb.Bounds.deserializeBinaryFromReader);
      msg.setBounds(value);
      break;
    case 6:
      var value = new gpx_pb.Point;
      reader.readMessage(value,gpx_pb.Point.deserializeBinaryFromReader);
      msg.setMaxspeedpoint(value);
      break;
    case 7:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDuration(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAveragespeed(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDistance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.domain.PathCreatedFromGpxEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.domain.PathCreatedFromGpxEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.domain.PathCreatedFromGpxEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.ProtoUUID.serializeBinaryToWriter
    );
  }
  f = message.getTrack();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      gpx_pb.Track.serializeBinaryToWriter
    );
  }
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getBounds();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      gpx_pb.Bounds.serializeBinaryToWriter
    );
  }
  f = message.getMaxspeedpoint();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      gpx_pb.Point.serializeBinaryToWriter
    );
  }
  f = message.getDuration();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getAveragespeed();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getDistance();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
};


/**
 * optional path.common.ProtoUUID id = 1;
 * @return {?proto.path.common.ProtoUUID}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getId = function() {
  return /** @type{?proto.path.common.ProtoUUID} */ (
    jspb.Message.getWrapperField(this, common_pb.ProtoUUID, 1));
};


/**
 * @param {?proto.path.common.ProtoUUID|undefined} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
*/
proto.path.domain.PathCreatedFromGpxEvent.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional path.gpx.Track track = 3;
 * @return {?proto.path.gpx.Track}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getTrack = function() {
  return /** @type{?proto.path.gpx.Track} */ (
    jspb.Message.getWrapperField(this, gpx_pb.Track, 3));
};


/**
 * @param {?proto.path.gpx.Track|undefined} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
*/
proto.path.domain.PathCreatedFromGpxEvent.prototype.setTrack = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.clearTrack = function() {
  return this.setTrack(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.hasTrack = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
*/
proto.path.domain.PathCreatedFromGpxEvent.prototype.setTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.clearTime = function() {
  return this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.hasTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional path.gpx.Bounds bounds = 5;
 * @return {?proto.path.gpx.Bounds}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getBounds = function() {
  return /** @type{?proto.path.gpx.Bounds} */ (
    jspb.Message.getWrapperField(this, gpx_pb.Bounds, 5));
};


/**
 * @param {?proto.path.gpx.Bounds|undefined} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
*/
proto.path.domain.PathCreatedFromGpxEvent.prototype.setBounds = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.clearBounds = function() {
  return this.setBounds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.hasBounds = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional path.gpx.Point maxSpeedPoint = 6;
 * @return {?proto.path.gpx.Point}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getMaxspeedpoint = function() {
  return /** @type{?proto.path.gpx.Point} */ (
    jspb.Message.getWrapperField(this, gpx_pb.Point, 6));
};


/**
 * @param {?proto.path.gpx.Point|undefined} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
*/
proto.path.domain.PathCreatedFromGpxEvent.prototype.setMaxspeedpoint = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.clearMaxspeedpoint = function() {
  return this.setMaxspeedpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.hasMaxspeedpoint = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Duration duration = 7;
 * @return {?proto.google.protobuf.Duration}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 7));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
*/
proto.path.domain.PathCreatedFromGpxEvent.prototype.setDuration = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.clearDuration = function() {
  return this.setDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.hasDuration = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional double averageSpeed = 8;
 * @return {number}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getAveragespeed = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.setAveragespeed = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double distance = 9;
 * @return {number}
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.getDistance = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.path.domain.PathCreatedFromGpxEvent} returns this
 */
proto.path.domain.PathCreatedFromGpxEvent.prototype.setDistance = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.domain.PathRenamedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.path.domain.PathRenamedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.domain.PathRenamedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.domain.PathRenamedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && common_pb.ProtoUUID.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.domain.PathRenamedEvent}
 */
proto.path.domain.PathRenamedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.domain.PathRenamedEvent;
  return proto.path.domain.PathRenamedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.domain.PathRenamedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.domain.PathRenamedEvent}
 */
proto.path.domain.PathRenamedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.ProtoUUID;
      reader.readMessage(value,common_pb.ProtoUUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.domain.PathRenamedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.domain.PathRenamedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.domain.PathRenamedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.domain.PathRenamedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.ProtoUUID.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional path.common.ProtoUUID id = 1;
 * @return {?proto.path.common.ProtoUUID}
 */
proto.path.domain.PathRenamedEvent.prototype.getId = function() {
  return /** @type{?proto.path.common.ProtoUUID} */ (
    jspb.Message.getWrapperField(this, common_pb.ProtoUUID, 1));
};


/**
 * @param {?proto.path.common.ProtoUUID|undefined} value
 * @return {!proto.path.domain.PathRenamedEvent} returns this
*/
proto.path.domain.PathRenamedEvent.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathRenamedEvent} returns this
 */
proto.path.domain.PathRenamedEvent.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathRenamedEvent.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.path.domain.PathRenamedEvent.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.path.domain.PathRenamedEvent} returns this
 */
proto.path.domain.PathRenamedEvent.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path.domain.PathRemovedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.path.domain.PathRemovedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path.domain.PathRemovedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.domain.PathRemovedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && common_pb.ProtoUUID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path.domain.PathRemovedEvent}
 */
proto.path.domain.PathRemovedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path.domain.PathRemovedEvent;
  return proto.path.domain.PathRemovedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path.domain.PathRemovedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path.domain.PathRemovedEvent}
 */
proto.path.domain.PathRemovedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.ProtoUUID;
      reader.readMessage(value,common_pb.ProtoUUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path.domain.PathRemovedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path.domain.PathRemovedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path.domain.PathRemovedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path.domain.PathRemovedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.ProtoUUID.serializeBinaryToWriter
    );
  }
};


/**
 * optional path.common.ProtoUUID id = 1;
 * @return {?proto.path.common.ProtoUUID}
 */
proto.path.domain.PathRemovedEvent.prototype.getId = function() {
  return /** @type{?proto.path.common.ProtoUUID} */ (
    jspb.Message.getWrapperField(this, common_pb.ProtoUUID, 1));
};


/**
 * @param {?proto.path.common.ProtoUUID|undefined} value
 * @return {!proto.path.domain.PathRemovedEvent} returns this
*/
proto.path.domain.PathRemovedEvent.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.path.domain.PathRemovedEvent} returns this
 */
proto.path.domain.PathRemovedEvent.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.path.domain.PathRemovedEvent.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.path.domain);
